version: '3.8'

services:
  web:
    container_name: converter_webapp
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 converter_webapp.wsgi"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - example.env
    depends_on:
      - db

  db:
    container_name: converter_db
    image: postgres:15
    env_file:
      - example.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume: