# Generated by Django 4.2.1 on 2025-05-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='documentation',
            new_name='doc_type',
        ),
        migrations.AlterField(
            model_name='album',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
