# Generated by Django 4.2.1 on 2025-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_documentation_album_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
